language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true
before_install:
  # Set up anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

  # Clone relevant repositories
  - sudo apt-get update -qq
  - sudo apt-get install git 
  - cd ..
  - git clone https://github.com/GreenGroup/RMG-database.git
  - git clone https://github.com/GreenGroup/PyDAS.git
  - git clone https://github.com/GreenGroup/PyDQED.git

install:
  # Install non-RMG dependencies via conda
  - conda install --yes -c rmg gcc libgcc python numpy cython==0.21 matplotlib rdkit quantities scipy xlwt markupsafe jinja2 pyparsing pydot nose coverage guppy gprof2dot cairo cairocffi openbabel psutil symmetry mopac setuptools boost==1.56.0  

  - cd $TRAVIS_BUILD_DIR
  - cd ..
  - cd PyDAS
  - cd daspk31
  - wget http://www.engineering.ucsb.edu/~cse/Software/daspk31.tgz
  - cd ..
  - make F77=gfortran
  - make install
  - cd ..
  - cd PyDQED
  - make F77=gfortran
  - make install
  - cd ..
  - cd $TRAVIS_BUILD_DIR
  - make
script: 
  - make test
  - make eg1
