language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

  - cd RMG-Py

install:
  - conda install --yes -c rmg rmg rmgdatabase

script: 
  - nosetests --nocapture --nologcapture --all-modules --verbose --with-coverage --cover-inclusive --cover-package=rmgpy --cover-erase --cover-html --cover-html-dir=testing/coverage --exe rmgpy
  - cd examples/rmg/minimal
  - rmg.py input.py
  - make eg5
  - make eg6
