# For conda build
package:
  name: rmg
  version: "0.1.0"

source:
  path: .

build:
  number: 1

requirements:
  build:
    - gcc # [unix]
    - python
    - setuptools
    - cython ==0.21
    - numpy
    - pydas
    - pydqed
    - boost ==1.56.0
    - rdkit
    - libgcc # [unix]
    - numpy
    - matplotlib
    - rdkit
    - pydas
    - pydqed
    - quantities
    - scipy
    - xlwt
    - markupsafe
    - jinja2
    - argparse # [py26]
    - pyparsing # [not osx]
    - pydot # [not osx]
    - nose
    - coverage
    - guppy
    - gprof2dot
    - cairo
    - py2cairo
    - openbabel # [not osx]
    - psutil
  run:
    - libgcc # [unix]
    - python
    - numpy
    - cython ==0.21
    - matplotlib
    - rdkit
    - pydas
    - pydqed
    - quantities
    - scipy
    - xlwt
    - markupsafe
    - jinja2
    - argparse # [py26]
    - pyparsing # [not osx]
    - pydot # [not osx]
    - nose
    - coverage
    - guppy
    - gprof2dot
    - py2cairo
    - cairo
    - openbabel # [not osx]
    - psutil
test:
  requires:
    - nose
  imports:
    - rmgpy

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
